-- =====================================================================
-- RuLaFHub Alpha Restruktur - Migration 001
-- Jalankan SQL ini di Supabase Dashboard -> SQL Editor
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) TOKEN ID (Privasi-First NFC / QR)
--    Profil murid mendapat token rawak (cth: RULAF-SEC-xxxxxx).
--    Fizikal NFC chip / QR HANYA mengandungi token ini - TIADA data
--    peribadi (MyKid / no-tel ibu bapa) pada kad.
-- ---------------------------------------------------------------------
ALTER TABLE public.profil_pengguna
    ADD COLUMN IF NOT EXISTS token_id TEXT;

-- Token mestilah unik supaya pemetaan 1:1 kekal selamat
CREATE UNIQUE INDEX IF NOT EXISTS idx_profil_pengguna_token
    ON public.profil_pengguna (token_id)
    WHERE token_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- 2) RVIDS - MEKANISME PENGAJARAN (Short-form video micro-learning)
--    pautan_video menyimpan URL publik MP4 dari bucket "modul-rulaf"
--    (cawangan storage folder /rvids/), atau pautan luaran.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.rulaf_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tajuk_video TEXT NOT NULL DEFAULT '',
    pautan_video TEXT NOT NULL DEFAULT '',
    kategori TEXT DEFAULT 'Jawi',
    pencipta TEXT DEFAULT '',
    is_aktif BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.rulaf_videos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rulaf_videos_select_publik"
    ON public.rulaf_videos FOR SELECT
    USING (true);

CREATE POLICY "rulaf_videos_insert"
    ON public.rulaf_videos FOR INSERT
    WITH CHECK (true);

-- ---------------------------------------------------------------------
-- 3) RULAFBOX_EDARAN - LOG EDARAN BBM + SIAP MODUL (NFC / QR)
--    Mencatat setiap pengimbasan kad murid semasa pengagihan BBM
--    dan pengesahan siap modul.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.rulafbox_edaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id TEXT DEFAULT '',
    mykid TEXT DEFAULT '',
    nama_murid TEXT DEFAULT '',
    bahan_bbm_id BIGINT DEFAULT NULL,
    bahan_bbm_tajuk TEXT DEFAULT '',
    tarikh_edaran DATE DEFAULT CURRENT_DATE,
    status_siap_modul BOOLEAN DEFAULT FALSE,
    kaedah TEXT DEFAULT 'nfc',            -- 'nfc' | 'qr'
    diimbas_oleh TEXT DEFAULT '',         -- email guru
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.rulafbox_edaran ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rulafbox_edaran_select"
    ON public.rulafbox_edaran FOR SELECT
    USING (true);

CREATE POLICY "rulafbox_edaran_insert"
    ON public.rulafbox_edaran FOR INSERT
    WITH CHECK (true);

-- ---------------------------------------------------------------------
-- 4) VIEW LOG EDARAN DENGAN MAKLUMAT MURID (opsional, untuk pentadbir)
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_rulafbox_edaran AS
SELECT
    e.id,
    e.token_id,
    e.mykid,
    e.nama_murid,
    e.bahan_bbm_id,
    e.bahan_bbm_tajuk,
    e.tarikh_edaran,
    e.status_siap_modul,
    e.kaedah,
    e.diimbas_oleh,
    e.created_at,
    p.nama AS nama_profil,
    p.kelas AS kelas_resmi
FROM public.rulafbox_edaran e
LEFT JOIN public.profil_pengguna p ON p.email = e.diimbas_oleh;

-- ---------------------------------------------------------------------
-- 5) VIEW LEADERBOARD TERKUMPUL (AGGREGATED) - Carta Juara RuLaF
--    Mengumpulkan total skor per murid dari semua sesi permainan
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_leaderboard_terkumpul AS
SELECT
    l.mykid,
    l.nama_murid,
    SUM(l.skor) AS total_skor,
    MAX(l.level_capai) AS level_tertinggi,
    SUM(l.jawapan_betul) AS total_betul,
    SUM(l.jawapan_salah) AS total_salah,
    COUNT(*) AS bilangan_sesi,
    MAX(l.tarikh) AS tarikh_terkini
FROM public.rulaf_leaderboard l
GROUP BY l.mykid, l.nama_murid
ORDER BY total_skor DESC;

-- ---------------------------------------------------------------------
-- PERHATIAN RLS:
--   * profil_pengguna: anon HANYA dibenarkan SELECT + UPDATE (PATCH)
--     (INSERT upsert DITOLAK - konsisten dengan keadaan semasa).
--   * Untuk menambah token_id, guna PATCH seperti aplikasi lakukan.
--   * rulaf_videos & rulafbox_edaran: dibenarkan SELECT + INSERT
--     supaya aplikasi (kunci ANON) boleh berfungsi.
--   Jika perlu ketatkan, tukar "true" kepada peranan tertentu.
-- ---------------------------------------------------------------------